/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/'
      | '/(main)/benchmark'
      | '/(main)/cabs/'
      | '/(main)/cvs'
      | '/(main)/exrail'
      | '/(main)/logs'
      | '/(main)/sensors'
      | '/(main)/throttle'
      | '/(main)/turnouts/'
    >,
    '/(main)/': RouteRecordInfo<
      '/(main)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/benchmark': RouteRecordInfo<
      '/(main)/benchmark',
      '/benchmark',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/cabs/': RouteRecordInfo<
      '/(main)/cabs/',
      '/cabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/cvs': RouteRecordInfo<
      '/(main)/cvs',
      '/cvs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/exrail': RouteRecordInfo<
      '/(main)/exrail',
      '/exrail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/logs': RouteRecordInfo<
      '/(main)/logs',
      '/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/sensors': RouteRecordInfo<
      '/(main)/sensors',
      '/sensors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/throttle': RouteRecordInfo<
      '/(main)/throttle',
      '/throttle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/turnouts/': RouteRecordInfo<
      '/(main)/turnouts/',
      '/turnouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/'
        | '/(main)/benchmark'
        | '/(main)/cabs/'
        | '/(main)/cvs'
        | '/(main)/exrail'
        | '/(main)/logs'
        | '/(main)/sensors'
        | '/(main)/throttle'
        | '/(main)/turnouts/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(main)/index.vue': {
      routes:
        | '/(main)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/benchmark.vue': {
      routes:
        | '/(main)/benchmark'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/cabs/index.vue': {
      routes:
        | '/(main)/cabs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/cvs.vue': {
      routes:
        | '/(main)/cvs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/exrail.vue': {
      routes:
        | '/(main)/exrail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/logs.vue': {
      routes:
        | '/(main)/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/sensors.vue': {
      routes:
        | '/(main)/sensors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/throttle.vue': {
      routes:
        | '/(main)/throttle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(main)/turnouts/index.vue': {
      routes:
        | '/(main)/turnouts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
